sudo: false

language: rust
rust:
    - stable
    - beta
    - nightly

after_success: 
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo doc &&
        git clone https://github.com/davisp/ghp-import &&
        ./ghp-import/ghp-import target/doc &&
        git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --no-verify --token ${CRATESIO_TOKEN}
